/*
 * This file is generated by jOOQ.
 */
package com.basketasia.model.tables.records;


import com.basketasia.model.tables.Configuration;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigurationRecord extends UpdatableRecordImpl<ConfigurationRecord> implements Record13<Integer, String, String, String, String, Integer, Integer, Timestamp, Timestamp, String, String, String, Integer> {

    private static final long serialVersionUID = -1259838484;

    /**
     * Setter for <code>kalagard_db_com.configuration.configuration_id</code>.
     */
    public void setConfigurationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.configuration_id</code>.
     */
    public Integer getConfigurationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.configuration_title</code>.
     */
    public void setConfigurationTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.configuration_title</code>.
     */
    public String getConfigurationTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.configuration_key</code>.
     */
    public void setConfigurationKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.configuration_key</code>.
     */
    public String getConfigurationKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.configuration_value</code>.
     */
    public void setConfigurationValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.configuration_value</code>.
     */
    public String getConfigurationValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.configuration_description</code>.
     */
    public void setConfigurationDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.configuration_description</code>.
     */
    public String getConfigurationDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.configuration_group_id</code>.
     */
    public void setConfigurationGroupId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.configuration_group_id</code>.
     */
    public Integer getConfigurationGroupId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.last_modified</code>.
     */
    public void setLastModified(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.last_modified</code>.
     */
    public Timestamp getLastModified() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.date_added</code>.
     */
    public void setDateAdded(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.date_added</code>.
     */
    public Timestamp getDateAdded() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.use_function</code>.
     */
    public void setUseFunction(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.use_function</code>.
     */
    public String getUseFunction() {
        return (String) get(9);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.set_function</code>.
     */
    public void setSetFunction(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.set_function</code>.
     */
    public String getSetFunction() {
        return (String) get(10);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.store_id</code>.
     */
    public void setStoreId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.store_id</code>.
     */
    public String getStoreId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>kalagard_db_com.configuration.return_by_api</code>.
     */
    public void setReturnByApi(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>kalagard_db_com.configuration.return_by_api</code>.
     */
    public Integer getReturnByApi() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, Integer, Integer, Timestamp, Timestamp, String, String, String, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, Integer, Integer, Timestamp, Timestamp, String, String, String, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Configuration.CONFIGURATION.CONFIGURATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Configuration.CONFIGURATION.CONFIGURATION_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Configuration.CONFIGURATION.CONFIGURATION_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Configuration.CONFIGURATION.CONFIGURATION_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Configuration.CONFIGURATION.CONFIGURATION_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Configuration.CONFIGURATION.CONFIGURATION_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Configuration.CONFIGURATION.SORT_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Configuration.CONFIGURATION.LAST_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Configuration.CONFIGURATION.DATE_ADDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Configuration.CONFIGURATION.USE_FUNCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Configuration.CONFIGURATION.SET_FUNCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Configuration.CONFIGURATION.STORE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Configuration.CONFIGURATION.RETURN_BY_API;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getConfigurationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getConfigurationTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getConfigurationKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getConfigurationValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getConfigurationDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getConfigurationGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUseFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getSetFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getStoreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getReturnByApi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getConfigurationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getConfigurationTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getConfigurationKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getConfigurationValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getConfigurationDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getConfigurationGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUseFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getSetFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getStoreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getReturnByApi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value1(Integer value) {
        setConfigurationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value2(String value) {
        setConfigurationTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value3(String value) {
        setConfigurationKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value4(String value) {
        setConfigurationValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value5(String value) {
        setConfigurationDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value6(Integer value) {
        setConfigurationGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value7(Integer value) {
        setSortOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value8(Timestamp value) {
        setLastModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value9(Timestamp value) {
        setDateAdded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value10(String value) {
        setUseFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value11(String value) {
        setSetFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value12(String value) {
        setStoreId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord value13(Integer value) {
        setReturnByApi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9, String value10, String value11, String value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigurationRecord
     */
    public ConfigurationRecord() {
        super(Configuration.CONFIGURATION);
    }

    /**
     * Create a detached, initialised ConfigurationRecord
     */
    public ConfigurationRecord(Integer configurationId, String configurationTitle, String configurationKey, String configurationValue, String configurationDescription, Integer configurationGroupId, Integer sortOrder, Timestamp lastModified, Timestamp dateAdded, String useFunction, String setFunction, String storeId, Integer returnByApi) {
        super(Configuration.CONFIGURATION);

        set(0, configurationId);
        set(1, configurationTitle);
        set(2, configurationKey);
        set(3, configurationValue);
        set(4, configurationDescription);
        set(5, configurationGroupId);
        set(6, sortOrder);
        set(7, lastModified);
        set(8, dateAdded);
        set(9, useFunction);
        set(10, setFunction);
        set(11, storeId);
        set(12, returnByApi);
    }
}
