/*
 * This file is generated by jOOQ.
 */
package com.basketasia.model;


import com.basketasia.model.tables.Configuration;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>kalagard_db_com</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONFIGURATION_IDX_STORE_ID = Indexes0.CONFIGURATION_IDX_STORE_ID;
    public static final Index CONFIGURATION_PRIMARY = Indexes0.CONFIGURATION_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONFIGURATION_IDX_STORE_ID = Internal.createIndex("idx_store_id", Configuration.CONFIGURATION, new OrderField[] { Configuration.CONFIGURATION.STORE_ID }, false);
        public static Index CONFIGURATION_PRIMARY = Internal.createIndex("PRIMARY", Configuration.CONFIGURATION, new OrderField[] { Configuration.CONFIGURATION.CONFIGURATION_ID }, true);
    }
}
