/*
 * This file is generated by jOOQ.
 */
package com.basketasia.model;


import com.basketasia.model.tables.Configuration;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KalagardDbCom extends SchemaImpl {

    private static final long serialVersionUID = 1946319952;

    /**
     * The reference instance of <code>kalagard_db_com</code>
     */
    public static final KalagardDbCom KALAGARD_DB_COM = new KalagardDbCom();

    /**
     * The table <code>kalagard_db_com.configuration</code>.
     */
    public final Configuration CONFIGURATION = com.basketasia.model.tables.Configuration.CONFIGURATION;

    /**
     * No further instances allowed
     */
    private KalagardDbCom() {
        super("kalagard_db_com", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Configuration.CONFIGURATION);
    }
}
