/*
 * This file is generated by jOOQ.
 */
package com.basketasia.model;


import com.basketasia.model.tables.Configuration;
import com.basketasia.model.tables.records.ConfigurationRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>kalagard_db_com</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ConfigurationRecord, Integer> IDENTITY_CONFIGURATION = Identities0.IDENTITY_CONFIGURATION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConfigurationRecord> KEY_CONFIGURATION_PRIMARY = UniqueKeys0.KEY_CONFIGURATION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ConfigurationRecord, Integer> IDENTITY_CONFIGURATION = Internal.createIdentity(Configuration.CONFIGURATION, Configuration.CONFIGURATION.CONFIGURATION_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ConfigurationRecord> KEY_CONFIGURATION_PRIMARY = Internal.createUniqueKey(Configuration.CONFIGURATION, "KEY_configuration_PRIMARY", Configuration.CONFIGURATION.CONFIGURATION_ID);
    }
}
