/*
 * This file is generated by jOOQ.
 */
package com.basketasia.model;


import com.basketasia.model.tables.Configuration;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in kalagard_db_com
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kalagard_db_com.configuration</code>.
     */
    public static final Configuration CONFIGURATION = com.basketasia.model.tables.Configuration.CONFIGURATION;
}
